### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Atara6431** [jasonwynn10/SpectreZone#7] opened 2022-06-02 08:52 UTC
PocketMine-MP Crash Dump Thu Jun 2 16:48:24 AWST 2022

PocketMine-MP version: 4.4.0 [Protocol 503]
Git commit: f2299a562f1ca11fb9edec75b182e47ad1771bba
PHP version: 8.0.13
OS: WINNT, win

```
Error: Block ID 5963776 is out of bounds
File: pmsrc/src/block/BlockFactory
Line: 1054
Type: InvalidArgumentException
Backtrace:
#0 pmsrc/src/block/BlockFactory(1066): pocketmine\block\BlockFactory->get(int 5963776, int 0)
#1 pmsrc/src/world/World(1528): pocketmine\block\BlockFactory->fromFullBlock(int 95420416)
#2 pmsrc/src/entity/Entity(1245): pocketmine\world\World->getBlockAt(int 0, int 2, int 0)
#3 pmsrc/src/entity/Entity(1259): pocketmine\entity\Entity->getBlocksIntersected(float 0.001)
#4 pmsrc/src/entity/Entity(1279): pocketmine\entity\Entity->getBlocksAroundWithEntityInsideActions()
#5 pmsrc/src/entity/Entity(639): pocketmine\entity\Entity->checkBlockIntersections()
#6 pmsrc/src/entity/Living(609): pocketmine\entity\Entity->entityBaseTick(int 1)
#7 pmsrc/src/entity/Human(334): pocketmine\entity\Living->entityBaseTick(int 1)
#8 pmsrc/src/player/Player(1336): pocketmine\entity\Human->entityBaseTick(int 1)
#9 pmsrc/src/world/World(842): pocketmine\player\Player->onUpdate(int 1214)
#10 pmsrc/src/world/World(768): pocketmine\world\World->actuallyDoTick(int 1214)
#11 pmsrc/src/world/WorldManager(348): pocketmine\world\World->doTick(int 1214)
#12 pmsrc/src/Server(1813): pocketmine\world\WorldManager->tick(int 1214)
#13 pmsrc/src/Server(1695): pocketmine\Server->tick()
#14 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[31] C:\BaiduNetdiskDownload\Severs\, string[39] C:\BaiduNetdiskDownload\Severs\plugins\)
#16 pmsrc/src/PocketMine(327): pocketmine\server()
#17 pmsrc(11): require(string[75] phar://C:/BaiduNetdiskDownload/Severs/PocketMine-MP.phar/src/PocketMine.php)

Code:
[1045] 	 * Deserializes a block from the provided legacy ID and legacy meta.
[1046] 	 */
[1047] 	public function get(int $id, int $meta) : Block{
[1048] 		if($meta < 0 || $meta >= (1 << Block::INTERNAL_METADATA_BITS)){
[1049] 			throw new \InvalidArgumentException("Block meta value $meta is out of bounds");
[1050] 		}
[1051] 
[1052] 		$index = ($id << Block::INTERNAL_METADATA_BITS) | $meta;
[1053] 		if($index < 0 || $index >= $this->fullList->getSize()){
[1054] 			throw new \InvalidArgumentException("Block ID $id is out of bounds");
[1055] 		}
[1056] 		if($this->fullList[$index] !== null){
[1057] 			$block = clone $this->fullList[$index];
[1058] 		}else{
[1059] 			$block = new UnknownBlock(new BID($id, $meta), BreakInfo::instant());
[1060] 		}
[1061] 
[1062] 		return $block;
[1063] 	}
[1064] 
```

**Comment by jasonw4331** [comment] 2022-06-02 17:43
Duplicate of #5

**Closed as not planned by jasonw4331** 2022-06-02 17:43 UTC
